#cloud-config

# Manage package updates and installations
package_update: true
package_upgrade: true
packages:
  - openjdk-17-jdk

# Custom commands for setting up WildFly
runcmd:
  # Download and extract WildFly
  - wget https://github.com/wildfly/wildfly/releases/download/26.1.3.Final/wildfly-26.1.3.Final.tar.gz -O /tmp/wildfly.tar.gz
  - tar -xf /tmp/wildfly.tar.gz -C /opt
  - mv /opt/wildfly-*Final /opt/wildfly

  # Create and configure WildFly user
  - groupadd -r wildfly
  - useradd -r -g wildfly -d /opt/wildfly -s /sbin/nologin wildfly
  - chown -RH wildfly:wildfly /opt/wildfly

  # Configure WildFly installation
  - mkdir -p /etc/wildfly
  - cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf /etc/wildfly/
  - cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service /etc/systemd/system/
  - cp /opt/wildfly/docs/contrib/scripts/systemd/launch.sh /opt/wildfly/bin/
  - chmod +x /opt/wildfly/bin/*.sh

  # Enable and start the WildFly service
  - systemctl daemon-reload
  - systemctl enable wildfly
  - systemctl start wildfly
