name: Deploy to AKS

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches: main
    paths:
      - 'aks-deploy/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_ACR_NAME }}
  CONTAINER_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
  RESOURCE_GROUP: ${{ secrets.AKS_RG }}
  CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  DEPLOYMENT_MANIFEST_PATH: ${{ secrets.DEPLOYMENT_MANIFEST_PATH }}
  SERVICE_MANIFEST_PATH: ${{ secrets.SERVICE_MANIFEST_PATH }}

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: aks-prod
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENTRA_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          subscription-id: ${{ secrets.ENTRA_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest

      - name: Create k8s service
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.SERVICE_MANIFEST_PATH }}